### PR TITLE
Only require :access_token to be set if :enabled is true

### LINKED ISSUE #64: Require access token when enabled only
Rollbax requires an access token (and an environment) even when disabled or set to log mode.

I use the following configuration in config/config.exs:

    config :rollbax,
      access_token: {:system, "ROLLBAR_ACCESS_TOKEN"},
      environment: {:system, "ROLLBAR_ENVIRONMENT"}

I then set it to log mode for testing:

    config :rollbax,
      enabled: :log

`mix test` will still fail:

    ** (Mix) Could not start application rollbax: exited in: Rollbax.start(:normal, [])
        ** (EXIT) an exception was raised:
            ** (ArgumentError) system environment variable "ROLLBAR_ACCESS_TOKEN" is not set
                (rollbax) lib/rollbax.ex:136: Rollbax.fetch_and_resolve_config/1
                (rollbax) lib/rollbax.ex:54: Rollbax.start/2
                (kernel) application_master.erl:273: :application_master.start_it_old/4

I know that I can run `mix test --no-start` but other applications do need to start. I'm using Elixir 1.4 and could make it not infer the application by using `{:rollbax, "~> 0.8.1", runtime: Mix.env != :test}`.

All workarounds require more code to use Rollbax, though, so I thought it would be nice to make these required only when they really are.

I'm happy to submit a pull request for this change.

### PR DESCRIPTION
**Pull request by whatyouhide**
Closes #64.

\cc @ericmj

### CODE REVIEW

File: lib/rollbax.ex [hunk 1]
```diff
@@ -46,20 +46,22 @@ defmodule Rollbax do
...
-    custom  = get_config(:custom, %{})
-
-    token = fetch_and_resolve_config(:access_token)
-    envt  = fetch_and_resolve_config(:environment)
+    enabled = Application.get_env(:rollbax, :enabled, true)
+    custom = Application.get_env(:custom, %{})
+    environment = resolve_system_env(Application.fetch_env!(:rollbax, :environment))
+
+    access_token =
+      case enabled do
```
Comment (ericmj) [inline lib/rollbax.ex]: Not an `if`? :)

Comment (whatyouhide) [reply lib/rollbax.ex]: @ericmj `:enabled` can be `true | false | :log` so we need to know that it is `true` specifically :)
